
version: "3.9"  # Docker Swarm requires version 3.x
services:
  nfs-client:
    image: ubuntu:24.04
    user: "2000:2000"
    command: >
      sh -c "env | grep IP_NFS_SERVER && tail -f /dev/null"
    environment:
      - IP_NFS_SERVER=${IP_NFS_SERVER}
    volumes:
      - nfs-filestorage:/data/app/filestorge/
      - nfs-data:/data/app/data/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
volumes:
  nfs-filestorage:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${IP_NFS_SERVER},nfsvers=4,hard"
      device: ":/srv/nfs/shared/app/filestorage"

  nfs-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${IP_NFS_SERVER},nfsvers=4,hard"
      device: ":/srv/nfs/shared/app/data"
