

services:
  nfs-client:
    build: .
    image: ubuntu:24.04
    user: "2000:2000"
    container_name: nfs-client
    command: "tail -f /dev/null"
    volumes:
      - nfs-filestorage:/filestorge
volumes:
  nfs-filestorage:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${IP_NFS_SERVER},nfsvers=4,hard,rw"
      device: ":/srv/nfs/shared"
