

services:
  nfs-server:
    build: .
    image: nfs-server:01
    container_name: nfs-server
    privileged: true
    ports:
    - "111:111/tcp"
    - "111:111/udp"
    - "2049:2049/tcp"
    - "2049:2049/udp"
    - "20048:20048/tcp"
    - "20048:20048/udp"
    volumes:
      - /srv/nfs/shared/:/srv/nfs/shared/
